## Data Collection Notebook

In [2]:
import json
import os
import sys

import numpy as np
import pandas as pd

sys.path.append('../..')
from final_project.scripts.data_collection_utils import set_nulls, setup_categorical_type

<div style="padding: 0px 0px 0px 20px; border-left: 8px solid #ED9255; border-radius: 8px">
<h3>
    Reading CSV from EES - Explore Education Statistics

</h3>

    - https://explore-education-statistics.service.gov.uk/data-catalogue
    

</div>

In [4]:
rurality_path = os.path.abspath(os.path.join("NBO1_Data_Collection.ipynb/"+"../.."+"/data/raw/EES_attainment_by_rurality.csv"))
chars_path = os.path.abspath(os.path.join("NBO1_Data_Collection.ipynb/"+"../.."+"/data/raw/EES_attainment_by_characteristics.csv"))
retention_path = os.path.abspath(os.path.join("NBO1_Data_Collection.ipynb/"+"../.."+"/data/raw/EES_retention_by_region.csv"))
results_path = os.path.abspath(os.path.join("NBO1_Data_Collection.ipynb/"+"../.."+"/data/raw/EES_results_by_subject.csv"))
stem_path = os.path.abspath(os.path.join("NBO1_Data_Collection.ipynb/"+"../.."+"/data/raw/EES_stem_by_sex.csv"))

In [22]:
rurality_df = pd.read_csv(rurality_path)
chars_df = pd.read_csv(chars_path)
retention_df = pd.read_csv(retention_path)
results_df = pd.read_csv(results_path, low_memory=False)
stem_df = pd.read_csv(stem_path)

<div style="padding: 0px 0px 0px 20px; border-left: 8px solid #ED9255; border-radius: 8px">
<h3>
    Sorting out rurality_df

</h3>

    I will:
    - pull the important/ useful columns
    - deal with the custom null values "z", "x" and "c"
    - identify actual null values
    - give ordered categorical type to grade columns in order to perform numerical aggregation later (eg. min, max etc.)
    
</div>

In [23]:
rurality_df = rurality_df[["time_period", "version", "region_name", "rurality_name", "number_of_students_acad",
                           "number_of_students_alev", "number_of_students_potential", "aps_per_entry_grade_acad",
                           "aps_per_entry_grade_alev", "pc_achieving_atleast_two_alev", "pc_achieving_3_astar_to_a_alev"]]

rurality_df

,time_period,version,region_name,rurality_name,number_of_students_acad,number_of_students_alev,number_of_students_potential,aps_per_entry_grade_acad,aps_per_entry_grade_alev,pc_achieving_atleast_two_alev,pc_achieving_3_astar_to_a_alev
0,201920,Final,North East,Urban - Major conurbation,4444,4388,16513,B-,B-,81.472,17.538
1,201920,Final,West Midlands,Urban - Major conurbation,12258,12073,33043,B-,B-,82.117,16.95
2,201920,Final,East of England,Urban - Major conurbation,2980,2947,6759,B,B,88.497,22.976
3,201920,Final,East Midlands,Urban - Major conurbation,47,47,75,B-,B-,65.957,14.286
4,201920,Final,South West,Urban - Major conurbation,0,0,0,z,z,z,z
...,...,...,...,...,...,...,...,...,...,...,...
310,202324,Revised,North West,Unknown rurality,0,0,0,z,z,z,z
311,202324,Revised,Yorkshire and The Humber,Unknown rurality,0,0,0,z,z,z,z
312,202324,Revised,North East,Unknown rurality,0,0,0,z,z,z,z
313,202324,Revised,West Midlands,Unknown rurality,0,0,0,z,z,z,z
314,202324,Revised,East of England,Unknown rurality,0,0,0,z,z,z,z

In [47]:
rurality_df = rurality_df.map(set_nulls)

In [26]:
rurality_df = setup_categorical_type(rurality_df, "aps_per_entry_grade_acad")
rurality_df = setup_categorical_type(rurality_df, "aps_per_entry_grade_alev")

rurality_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 315 entries, 0 to 314
Data columns (total 11 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   time_period                     315 non-null    int64
 1   version                         315 non-null    object
 2   region_name                     315 non-null    object
 3   rurality_name                   315 non-null    object
 4   number_of_students_acad         315 non-null    int64
 5   number_of_students_alev         315 non-null    int64
 6   number_of_students_potential    315 non-null    int64
 7   aps_per_entry_grade_acad        315 non-null    category
 8   aps_per_entry_grade_alev        315 non-null    category
 9   pc_achieving_atleast_two_alev   215 non-null    float64
 10  pc_achieving_3_astar_to_a_alev  214 non-null    float64
dtypes: category(2), float64(2), int64(4), object(3)
memory usage: 24.3+ KB

In [31]:
rurality_df.groupby("region_name").apply(lambda x: x.isnull().sum(), include_groups=False)

,time_period,version,rurality_name,number_of_students_acad,number_of_students_alev,number_of_students_potential,aps_per_entry_grade_acad,aps_per_entry_grade_alev,pc_achieving_atleast_two_alev,pc_achieving_3_astar_to_a_alev
region_name,,,,,,,,,,
East Midlands,0,0,0,0,0,0,0,0,5,5
East of England,0,0,0,0,0,0,0,0,10,10
London,0,0,0,0,0,0,0,0,15,16
North East,0,0,0,0,0,0,0,0,15,15
North West,0,0,0,0,0,0,0,0,10,10
South East,0,0,0,0,0,0,0,0,10,10
South West,0,0,0,0,0,0,0,0,15,15
West Midlands,0,0,0,0,0,0,0,0,15,15
Yorkshire and The Humber,0,0,0,0,0,0,0,0,5,5

<div style="padding: 0px 0px 0px 20px; border-left: 8px solid #ED9255; border-radius: 8px">
<h3>
    Sorting out chars_df

</h3>

    I will:
    - pull the important/ useful columns
    - deal with the custom null values "z", "x" and "c"
    - identify actual null values
    - give ordered categorical type to grade columns in order to perform numerical aggregation later (eg. min, max etc.)
    
</div>

In [41]:
chars_df = chars_df[["time_period", "version", "region_name", "characteristic_type", "characteristic_value",
    "establishment_type", "number_of_students_acad", "number_of_students_alev", "number_of_students_potential",
    "aps_per_entry_grade_acad", "aps_per_entry_grade_alev", "pc_achieving_atleast_two_alev", "pc_achieving_3_astar_to_a_alev"]]
chars_df

,time_period,version,region_name,characteristic_type,characteristic_value,establishment_type,number_of_students_acad,number_of_students_alev,number_of_students_potential,aps_per_entry_grade_acad,aps_per_entry_grade_alev,pc_achieving_atleast_two_alev,pc_achieving_3_astar_to_a_alev
0,201920,Final,South East,Sex,Female,All state-funded schools and colleges,4317,4272,8343,B,B,87.079,18.097
1,201920,Final,East of England,Sex,Female,All state-funded schools and colleges,3888,3786,6977,B,B,90.755,25.079
2,201920,Final,South East,Sex,Female,All state-funded schools and colleges,4279,3786,8119,B,B,85.948,23.546
3,201920,Final,North West,Sex,Female,All state-funded schools and colleges,2486,2438,5728,B,B,90.279,20.884
4,201920,Final,East Midlands,Sex,Female,All state-funded schools and colleges,1400,1387,2672,B,B,91.492,19.161
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21029,202324,Revised,South East,All Students,All state-funded students,All state-funded schools and colleges,49986,48375,95158,B-,B-,84.688,15.976
21030,202324,Revised,East of England,All Students,All state-funded students,All state-funded schools and colleges,31366,30773,67239,C+,C+,85.871,14.403
21031,202324,Revised,London,All Students,All state-funded students,All state-funded schools and colleges,48514,47533,87911,B-,B-,88.564,16.177
21032,202324,Revised,North West,All Students,All state-funded students,All state-funded schools and colleges,33343,32853,78493,C+,C+,85.21,14.52
21033,202324,Revised,Yorkshire and The Humber,All Students,All state-funded students,All state-funded schools and colleges,23499,23136,57419,C+,C+,81.864,13.527

In [42]:
chars_df = chars_df.map(set_nulls)

In [43]:
chars_df = setup_categorical_type(chars_df, "aps_per_entry_grade_acad")
chars_df = setup_categorical_type(chars_df, "aps_per_entry_grade_alev")

chars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21034 entries, 0 to 21033
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   time_period                     21034 non-null  int64
 1   version                         21034 non-null  object
 2   region_name                     21034 non-null  object
 3   characteristic_type             21034 non-null  object
 4   characteristic_value            21034 non-null  object
 5   establishment_type              21034 non-null  object
 6   number_of_students_acad         20840 non-null  float64
 7   number_of_students_alev         20830 non-null  float64
 8   number_of_students_potential    21009 non-null  float64
 9   aps_per_entry_grade_acad        21034 non-null  category
 10  aps_per_entry_grade_alev        21034 non-null  category
 11  pc_achieving_atleast_two_alev   20515 non-null  float64
 12  pc_achieving_3_astar_to_a_alev  20399 non-null  float64
dtypes: category(2), float64(5), int64(1), object(5)
memory usage: 1.8+ MB

In [65]:
chars_df.groupby("time_period").apply(lambda x: x.isnull().sum(), include_groups=False)

,version,region_name,characteristic_type,characteristic_value,establishment_type,number_of_students_acad,number_of_students_alev,number_of_students_potential,aps_per_entry_grade_acad,aps_per_entry_grade_alev,pc_achieving_atleast_two_alev,pc_achieving_3_astar_to_a_alev
time_period,,,,,,,,,,,,
201920,0,0,0,0,0,33,33,0,0,0,88,103
202021,0,0,0,0,0,36,44,0,0,0,120,145
202122,0,0,0,0,0,56,54,0,0,0,107,144
202223,0,0,0,0,0,53,55,25,0,0,109,134
202324,0,0,0,0,0,16,18,0,0,0,95,109

<div style="padding: 0px 0px 0px 20px; border-left: 8px solid #ED9255; border-radius: 8px">
<h3>
    Sorting out retention_df

</h3>

    I will:
    - pull the important/ useful columns
    - deal with the custom null values "z", "x" and "c"
    - identify actual null values
    
</div>

In [55]:
retention_df = retention_df[["time_period", "version", "region_name", "exam_cohort", "student_count_year_1",
    "student_count_year_2", "retained", "retained_and_assessed", "returned_and_retained",
    "perc_retained", "perc_retained_and_assessed", "perc_returned_and_retained"]]
retention_df

,time_period,version,region_name,exam_cohort,student_count_year_1,student_count_year_2,retained,retained_and_assessed,returned_and_retained,perc_retained,perc_retained_and_assessed,perc_returned_and_retained
0,201920,Final,South East,A level,7813,6904,7018,6992,6039,89.825,89.492,87.471
1,201920,Final,East of England,A level,6728,6707,6435,6350,6313,95.645,94.382,94.126
2,201920,Final,South East,A level,6028,6003,5688,5560,5527,94.36,92.236,92.071
3,201920,Final,North West,A level,4562,4553,4108,4074,4016,90.048,89.303,88.206
4,201920,Final,East Midlands,A level,2397,2382,2240,2192,2117,93.45,91.448,88.875
...,...,...,...,...,...,...,...,...,...,...,...,...
4040,202324,Revised,South East,Technical certificate,1668,z,1393,1096,z,83.513,65.707,z
4041,202324,Revised,East of England,Technical certificate,1406,z,1204,887,z,85.633,63.087,z
4042,202324,Revised,London,Technical certificate,694,z,598,396,z,86.167,57.061,z
4043,202324,Revised,North West,Technical certificate,1864,z,1527,1221,z,81.921,65.504,z
4044,202324,Revised,Yorkshire and The Humber,Technical certificate,1007,z,846,625,z,84.012,62.066,z

In [57]:
retention_df = retention_df.map(set_nulls)

retention_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4045 entries, 0 to 4044
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   time_period                 4045 non-null   int64
 1   version                     4045 non-null   object
 2   region_name                 4045 non-null   object
 3   exam_cohort                 4045 non-null   object
 4   student_count_year_1        4045 non-null   int64
 5   student_count_year_2        3236 non-null   float64
 6   retained                    3829 non-null   float64
 7   retained_and_assessed       3829 non-null   float64
 8   returned_and_retained       3153 non-null   float64
 9   perc_retained               3829 non-null   float64
 10  perc_retained_and_assessed  3829 non-null   float64
 11  perc_returned_and_retained  3153 non-null   float64
dtypes: float64(7), int64(2), object(3)
memory usage: 379.3+ KB

In [64]:
retention_df.groupby("exam_cohort").apply(lambda x: x.isnull().sum(), include_groups=False)

,time_period,version,region_name,student_count_year_1,student_count_year_2,retained,retained_and_assessed,returned_and_retained,perc_retained,perc_retained_and_assessed,perc_returned_and_retained
exam_cohort,,,,,,,,,,,
A level,0,0,0,0,0,14,14,14,14,14,14
Academic,0,0,0,0,0,14,14,14,14,14,14
Applied general,0,0,0,0,0,18,18,18,18,18,18
Tech level,0,0,0,0,0,37,37,37,37,37,37
Technical certificate,0,0,0,0,809,133,133,809,133,133,809

<div style="padding: 0px 0px 0px 20px; border-left: 8px solid #ED9255; border-radius: 8px">
<h3>
    Sorting out results_df

</h3>

    I will:
    - pull the important/ useful columns
    - deal with the custom null values "z", "x" and "c"
    - identify actual null values
    - give ordered categorical type to grade columns in order to perform numerical aggregation later (eg. min, max etc.)

    
</div>

In [80]:
results_df = results_df[["time_period", "version", "region_name", "qualification", "subject_name",
    "subject_area", "entry_count", "astar_grade_achieved", "a_grade_achieved", "b_grade_achieved",
    "c_grade_achieved", "d_grade_achieved", "e_grade_achieved", "u_grade_achieved",
    "astar_a_grade_achieved", "astar_b_grade_achieved", "astar_c_grade_achieved", "astar_d_grade_achieved",
    "astar_e_grade_achieved"]]

results_df

,time_period,version,region_name,qualification,subject_name,subject_area,entry_count,astar_grade_achieved,a_grade_achieved,b_grade_achieved,c_grade_achieved,d_grade_achieved,e_grade_achieved,u_grade_achieved,astar_a_grade_achieved,astar_b_grade_achieved,astar_c_grade_achieved,astar_d_grade_achieved,astar_e_grade_achieved
0,202223,Revised,London,AS level,Additional Mathematics,Maths,z,z,z,z,z,z,z,z,z,z,z,z,z
1,202223,Revised,London,AS level,Additional Mathematics,Maths,z,z,z,z,z,z,z,z,z,z,z,z,z
2,202223,Revised,London,AS level,Additional Mathematics,Maths,z,z,z,z,z,z,z,z,z,z,z,z,z
3,202223,Revised,London,AS level,Additional Mathematics,Maths,z,z,z,z,z,z,z,z,z,z,z,z,z
4,202223,Revised,London,AS level,Additional Mathematics,Maths,z,z,z,z,z,z,z,z,z,z,z,z,z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175703,202324,Revised,London,AS level,Total Biology,Science - Biology,1229,0,337,198,173,199,124,185,337,535,708,907,1031
175704,202324,Revised,London,AS level,Environmental Science,Science - other,0,0,0,0,0,0,0,0,0,0,0,0,0
175705,202324,Revised,London,AS level,Film Studies,Arts,67,0,11,23,20,6,3,2,11,34,54,60,63
175706,202324,Revised,London,AS level,Total Law,Law,62,0,6,2,9,8,21,15,6,8,17,25,46
175707,202324,Revised,London,AS level,Total Psychology,Psychology,1164,0,274,177,226,183,136,152,274,451,677,860,996

In [81]:
results_df = results_df.map(set_nulls)

results_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175708 entries, 0 to 175707
Data columns (total 19 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   time_period             175708 non-null  int64
 1   version                 175708 non-null  object
 2   region_name             175708 non-null  object
 3   qualification           175708 non-null  object
 4   subject_name            175708 non-null  object
 5   subject_area            175708 non-null  object
 6   entry_count             158397 non-null  float64
 7   astar_grade_achieved    158397 non-null  float64
 8   a_grade_achieved        158397 non-null  float64
 9   b_grade_achieved        158397 non-null  float64
 10  c_grade_achieved        158397 non-null  float64
 11  d_grade_achieved        158397 non-null  float64
 12  e_grade_achieved        158397 non-null  float64
 13  u_grade_achieved        158397 non-null  float64
 14  astar_a_grade_achieved  158397 non-null  float64
 15  astar_b_grade_achieved  158397 non-null  float64
 16  astar_c_grade_achieved  158397 non-null  float64
 17  astar_d_grade_achieved  158397 non-null  float64
 18  astar_e_grade_achieved  158397 non-null  float64
dtypes: float64(13), int64(1), object(5)
memory usage: 25.5+ MB

In [92]:
results_df.groupby("region_name").apply(lambda x: x.isnull().sum(), include_groups=False)

,time_period,version,qualification,subject_name,subject_area,entry_count,astar_grade_achieved,a_grade_achieved,b_grade_achieved,c_grade_achieved,d_grade_achieved,e_grade_achieved,u_grade_achieved,astar_a_grade_achieved,astar_b_grade_achieved,astar_c_grade_achieved,astar_d_grade_achieved,astar_e_grade_achieved
region_name,,,,,,,,,,,,,,,,,,
East Midlands,0,0,0,0,0,1175,1175,1175,1175,1175,1175,1175,1175,1175,1175,1175,1175,1175
East of England,0,0,0,0,0,1284,1284,1284,1284,1284,1284,1284,1284,1284,1284,1284,1284,1284
London,0,0,0,0,0,3638,3638,3638,3638,3638,3638,3638,3638,3638,3638,3638,3638,3638
North East,0,0,0,0,0,1391,1391,1391,1391,1391,1391,1391,1391,1391,1391,1391,1391,1391
North West,0,0,0,0,0,2654,2654,2654,2654,2654,2654,2654,2654,2654,2654,2654,2654,2654
South East,0,0,0,0,0,2140,2140,2140,2140,2140,2140,2140,2140,2140,2140,2140,2140,2140
South West,0,0,0,0,0,1712,1712,1712,1712,1712,1712,1712,1712,1712,1712,1712,1712,1712
West Midlands,0,0,0,0,0,1605,1605,1605,1605,1605,1605,1605,1605,1605,1605,1605,1605,1605
Yorkshire and The Humber,0,0,0,0,0,1712,1712,1712,1712,1712,1712,1712,1712,1712,1712,1712,1712,1712

<div style="padding: 0px 0px 0px 20px; border-left: 8px solid #ED9255; border-radius: 8px">
<h3>
    Sorting out stem_df

</h3>

    I will:
    - pull the important/ useful columns
    - deal with the custom null values "z", "x" and "c"
    - identify actual null values
    
</div>

In [95]:
stem_df = stem_df[["time_period", "version", "region_name", "characteristic_sex",
                   "sub_name_comb", "num_maths_science", "num_entered_comb_and_no_other_matsci",
                  "num_entered_matsci_subjects_including_comb"]]

stem_df

,time_period,version,region_name,characteristic_sex,sub_name_comb,num_maths_science,num_entered_comb_and_no_other_matsci,num_entered_matsci_subjects_including_comb
0,201920,Final,North West,Female,Maths & Further Maths & Biology & Chemistry & ...,6,0,0
1,201920,Final,East Midlands,Female,Maths & Further Maths & Biology & Chemistry & ...,6,0,0
2,201920,Final,East Midlands,Female,Maths & Further Maths & Biology & Chemistry & ...,6,0,0
3,201920,Final,East of England,Female,Maths & Further Maths & Biology & Chemistry & ...,6,0,0
4,201920,Final,East Midlands,Female,Maths & Further Maths & Biology & Chemistry & ...,6,0,0
...,...,...,...,...,...,...,...,...
171673,202324,Revised,East of England,All,Total Students,Total Students,30322,30322
171674,202324,Revised,East Midlands,All,Total Students,Total Students,19815,19815
171675,202324,Revised,South West,All,Total Students,Total Students,22252,22252
171676,202324,Revised,South East,All,Total Students,Total Students,47753,47753
171677,202324,Revised,London,All,Total Students,Total Students,46893,46893

In [100]:
stem_df = stem_df.map(set_nulls)

stem_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171678 entries, 0 to 171677
Data columns (total 8 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   time_period                                 171678 non-null  int64
 1   version                                     171678 non-null  object
 2   region_name                                 171678 non-null  object
 3   characteristic_sex                          171678 non-null  object
 4   sub_name_comb                               171678 non-null  object
 5   num_maths_science                           171678 non-null  object
 6   num_entered_comb_and_no_other_matsci        171678 non-null  int64
 7   num_entered_matsci_subjects_including_comb  171678 non-null  int64
dtypes: int64(3), object(5)
memory usage: 10.5+ MB

In [101]:
stem_df.groupby("region_name").apply(lambda x: x.isnull().sum(), include_groups=False)

,time_period,version,characteristic_sex,sub_name_comb,num_maths_science,num_entered_comb_and_no_other_matsci,num_entered_matsci_subjects_including_comb
region_name,,,,,,,
East Midlands,0,0,0,0,0,0,0
East of England,0,0,0,0,0,0,0
London,0,0,0,0,0,0,0
North East,0,0,0,0,0,0,0
North West,0,0,0,0,0,0,0
South East,0,0,0,0,0,0,0
South West,0,0,0,0,0,0,0
West Midlands,0,0,0,0,0,0,0
Yorkshire and The Humber,0,0,0,0,0,0,0